---
- name: Override nginx.conf config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"

- name: Config vhosts
  copy: 
    src: ../files/
    dest: /etc/nginx/conf.d/

- name: validate and apply
  notify:
   - validate nginx
   - reload nginx
