---
# handlers file for nginx
- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: true

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: validate nginx
  command: nginx -t
  changed_when: false
